# Generated by Django 5.1.6 on 2025-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
