# Generated by Django 5.1.6 on 2025-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
